
package fr.afcepf.atod26.ws.supertp.controleur.proxys.gestionimage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "gestionImage", targetNamespace = "http://fichier.supertp.webservice.atod26.afcepf.fr", wsdlLocation = "http://localhost:18080/WS-SuperTP-Fichier/gestionImage?wsdl")
public class GestionImage
    extends Service
{

    private final static URL GESTIONIMAGE_WSDL_LOCATION;
    private final static WebServiceException GESTIONIMAGE_EXCEPTION;
    private final static QName GESTIONIMAGE_QNAME = new QName("http://fichier.supertp.webservice.atod26.afcepf.fr", "gestionImage");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/WS-SuperTP-Fichier/gestionImage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONIMAGE_WSDL_LOCATION = url;
        GESTIONIMAGE_EXCEPTION = e;
    }

    public GestionImage() {
        super(__getWsdlLocation(), GESTIONIMAGE_QNAME);
    }

    public GestionImage(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONIMAGE_QNAME, features);
    }

    public GestionImage(URL wsdlLocation) {
        super(wsdlLocation, GESTIONIMAGE_QNAME);
    }

    public GestionImage(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONIMAGE_QNAME, features);
    }

    public GestionImage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionImage(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGestionImage
     */
    @WebEndpoint(name = "GestionImageImpPort")
    public IGestionImage getGestionImageImpPort() {
        return super.getPort(new QName("http://fichier.supertp.webservice.atod26.afcepf.fr", "GestionImageImpPort"), IGestionImage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGestionImage
     */
    @WebEndpoint(name = "GestionImageImpPort")
    public IGestionImage getGestionImageImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fichier.supertp.webservice.atod26.afcepf.fr", "GestionImageImpPort"), IGestionImage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONIMAGE_EXCEPTION!= null) {
            throw GESTIONIMAGE_EXCEPTION;
        }
        return GESTIONIMAGE_WSDL_LOCATION;
    }

}
