
package fr.afcepf.atod26.ws.supertp.controleur.proxys.daorechercher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "daoRecherche", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", wsdlLocation = "http://localhost:18080/WS-SuperTP-Data/daoRecherche/DaoRechercherImpl?wsdl")
public class DaoRecherche
    extends Service
{

    private final static URL DAORECHERCHE_WSDL_LOCATION;
    private final static WebServiceException DAORECHERCHE_EXCEPTION;
    private final static QName DAORECHERCHE_QNAME = new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "daoRecherche");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/WS-SuperTP-Data/daoRecherche/DaoRechercherImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAORECHERCHE_WSDL_LOCATION = url;
        DAORECHERCHE_EXCEPTION = e;
    }

    public DaoRecherche() {
        super(__getWsdlLocation(), DAORECHERCHE_QNAME);
    }

    public DaoRecherche(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAORECHERCHE_QNAME, features);
    }

    public DaoRecherche(URL wsdlLocation) {
        super(wsdlLocation, DAORECHERCHE_QNAME);
    }

    public DaoRecherche(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAORECHERCHE_QNAME, features);
    }

    public DaoRecherche(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaoRecherche(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDaoRecherche
     */
    @WebEndpoint(name = "DaoRechercherImplPort")
    public IDaoRecherche getDaoRechercherImplPort() {
        return super.getPort(new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "DaoRechercherImplPort"), IDaoRecherche.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDaoRecherche
     */
    @WebEndpoint(name = "DaoRechercherImplPort")
    public IDaoRecherche getDaoRechercherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "DaoRechercherImplPort"), IDaoRecherche.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAORECHERCHE_EXCEPTION!= null) {
            throw DAORECHERCHE_EXCEPTION;
        }
        return DAORECHERCHE_WSDL_LOCATION;
    }

}
