
package fr.afcepf.atod26.webservice.supertp.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaoRechercherImplService", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", wsdlLocation = "http://localhost:18080/WS-SuperTP-Data/DaoRechercherImpl?wsdl")
public class DaoRechercherImplService
    extends Service
{

    private final static URL DAORECHERCHERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAORECHERCHERIMPLSERVICE_EXCEPTION;
    private final static QName DAORECHERCHERIMPLSERVICE_QNAME = new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "DaoRechercherImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/WS-SuperTP-Data/DaoRechercherImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAORECHERCHERIMPLSERVICE_WSDL_LOCATION = url;
        DAORECHERCHERIMPLSERVICE_EXCEPTION = e;
    }

    public DaoRechercherImplService() {
        super(__getWsdlLocation(), DAORECHERCHERIMPLSERVICE_QNAME);
    }

    public DaoRechercherImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAORECHERCHERIMPLSERVICE_QNAME, features);
    }

    public DaoRechercherImplService(URL wsdlLocation) {
        super(wsdlLocation, DAORECHERCHERIMPLSERVICE_QNAME);
    }

    public DaoRechercherImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAORECHERCHERIMPLSERVICE_QNAME, features);
    }

    public DaoRechercherImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaoRechercherImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDaoRecherche
     */
    @WebEndpoint(name = "DaoRechercherImplPort")
    public IDaoRecherche getDaoRechercherImplPort() {
        return super.getPort(new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "DaoRechercherImplPort"), IDaoRecherche.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDaoRecherche
     */
    @WebEndpoint(name = "DaoRechercherImplPort")
    public IDaoRecherche getDaoRechercherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.supertp.webservice.atod26.afcepf.fr", "DaoRechercherImplPort"), IDaoRecherche.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAORECHERCHERIMPLSERVICE_EXCEPTION!= null) {
            throw DAORECHERCHERIMPLSERVICE_EXCEPTION;
        }
        return DAORECHERCHERIMPLSERVICE_WSDL_LOCATION;
    }

}
