
package fr.afcepf.atod26.webservice.supertp.ejb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDaoRecherche", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDaoRecherche {


    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.atod26.webservice.supertp.ejb.MarqueDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherToutesLesMarques", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.ejb.RechercherToutesLesMarques")
    @ResponseWrapper(localName = "rechercherToutesLesMarquesResponse", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.ejb.RechercherToutesLesMarquesResponse")
    public List<MarqueDTO> rechercherToutesLesMarques();

    /**
     * 
     * @param paramMarqueDTO
     * @return
     *     returns java.util.List<fr.afcepf.atod26.webservice.supertp.ejb.ProduitDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherProduits", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.ejb.RechercherProduits")
    @ResponseWrapper(localName = "rechercherProduitsResponse", targetNamespace = "http://ejb.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.ejb.RechercherProduitsResponse")
    public List<ProduitDTO> rechercherProduits(
        @WebParam(name = "paramMarqueDTO", targetNamespace = "")
        MarqueDTO paramMarqueDTO);

}
