
package fr.afcepf.atod26.webservice.supertp.fichier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGestionImage", targetNamespace = "http://fichier.supertp.webservice.atod26.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGestionImage {


    /**
     * 
     * @param idMarque
     * @param idProduit
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "imageChaine", targetNamespace = "")
    @RequestWrapper(localName = "recupereImage", targetNamespace = "http://fichier.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.fichier.RecupereImage")
    @ResponseWrapper(localName = "recupereImageResponse", targetNamespace = "http://fichier.supertp.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.supertp.fichier.RecupereImageResponse")
    public List<String> recupereImage(
        @WebParam(name = "idMarque", targetNamespace = "")
        Integer idMarque,
        @WebParam(name = "idProduit", targetNamespace = "")
        Integer idProduit);

}
