
package fr.afcepf.atod26.webservice.supertp.controler;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webServiceControleur", targetNamespace = "http://controler.supertp.webservice.atod26.afcepf.fr", wsdlLocation = "http://localhost:18080/WS-SuperTP-Controleur/webServiceControleur?wsdl")
public class WebServiceControleur
    extends Service
{

    private final static URL WEBSERVICECONTROLEUR_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECONTROLEUR_EXCEPTION;
    private final static QName WEBSERVICECONTROLEUR_QNAME = new QName("http://controler.supertp.webservice.atod26.afcepf.fr", "webServiceControleur");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/WS-SuperTP-Controleur/webServiceControleur?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECONTROLEUR_WSDL_LOCATION = url;
        WEBSERVICECONTROLEUR_EXCEPTION = e;
    }

    public WebServiceControleur() {
        super(__getWsdlLocation(), WEBSERVICECONTROLEUR_QNAME);
    }

    public WebServiceControleur(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECONTROLEUR_QNAME, features);
    }

    public WebServiceControleur(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECONTROLEUR_QNAME);
    }

    public WebServiceControleur(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECONTROLEUR_QNAME, features);
    }

    public WebServiceControleur(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceControleur(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IControllerWS
     */
    @WebEndpoint(name = "ControlerWSImplPort")
    public IControllerWS getControlerWSImplPort() {
        return super.getPort(new QName("http://controler.supertp.webservice.atod26.afcepf.fr", "ControlerWSImplPort"), IControllerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IControllerWS
     */
    @WebEndpoint(name = "ControlerWSImplPort")
    public IControllerWS getControlerWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controler.supertp.webservice.atod26.afcepf.fr", "ControlerWSImplPort"), IControllerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECONTROLEUR_EXCEPTION!= null) {
            throw WEBSERVICECONTROLEUR_EXCEPTION;
        }
        return WEBSERVICECONTROLEUR_WSDL_LOCATION;
    }

}
