
package fr.afcepf.atod26.webservice.supertp.controler;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSControlerException", targetNamespace = "http://controler.supertp.webservice.atod26.afcepf.fr")
public class WSControlerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WSControlerException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WSControlerException_Exception(String message, WSControlerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WSControlerException_Exception(String message, WSControlerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.atod26.webservice.supertp.controler.WSControlerException
     */
    public WSControlerException getFaultInfo() {
        return faultInfo;
    }

}
